---
title: "Introducción al proyecto de la asignatura"
author: 
  - name: "María Suárez Muñoz"
    orcid: 0000-0003-1765-6885
    email: maria.suarez.munoz@gmail.com
    affiliation: Departamento de Ingeniería Forestal, Universidad de Córdoba
date: 2025-01-07
sesion: 1
date-format: long
format: 
  revealjs: 
    multiplex: true
    logo: "images/logo-ugr.png"
    footer: Máster Universitario en Conservación, Gestión y Restauración de la Biodiversidad
    theme: [default, "../../custom_theme.scss"] 
    transition: fade
    background-transition: fade
    highlight-style: a11y
code-link: true
citation: true
---

# Presentación

- Aquí puedes ver el [pdf](nombre_archivo.pdf)

# Entregable: flujo de trabajo

## Objetivo

Construir un flujo de trabajo que describa un proceso complejo de análisis y procesamiento de información ambiental. El proceso puede ser tu proyecto fin de máster, el trabajo de la asignatura o cualquier otro análisis en el que estés trabajando. Para describirlo debes elaborar un esquema acompañado, si lo ves necesario, de un pequeño texto. Puedes utilizar herramientas digitales (https://app.diagrams.net/, PowerPoint) o un simple esquema hecho a mano para elaborar el esquema.

## Aspectos a valorar

- Identificación de datos y fuentes de información a utilizar: ¿cuáles son los datos o la información con la que vas a trabajar? ¿de dónde proceden?

- Identificación de procesos a llevar a cabo: ¿qué pasos o análisis realizarás?

- Caracterización de los procesos - ¿en qué consiste cada proceso de tu flujo de trabajo? Será importante describirlo con el nivel de detalle adecuado

- Coherencia de la secuencia: ¿en qué orden se realizarán los pasos?

- Uso de simbología: ¿se utilizan símbolos para describir los distintos elementos del esquema? ¿son estándar o siguen una tipología claramente descrita?

- Expresión escrita: el texto que acompaña al esquema es claro y permite comprender el proceso en mayor detalle.

## Evaluación

Tras la entrega inicial el trabajo entregado será devuelto con comentarios y sugerencias orientados a aclarar aspectos que se puedan mejorar. Tras ello se podrá hacer una segunda entrega que incorpore los aspectos mencionados en la primera evaluación. La segunda evaluación, por lo tanto, consistirá en analizar cómo se han incorporado mejoras o se ha aprendido del proceso.

# Recursos 

- [Santín, C., Madrigal, J., Cerdà, X., Pausas, J. 2023. Ciencia para las políticas públicas - Incendios forestales. Science4Policy. CSIC.]

- [Zamora, R., Pérez-Luque, A.J., Bonet, F.J., Barea-Azcón, J.M. y Aspizua, R. (editores). 2015. La huella del cambio global en Sierra Nevada: Retos para la conservación. Consejería de Medio Ambiente y Ordenación del Territorio. Junta de Andalucía. 208 pp.]

- [La huella del fuego](https://www.rtve.es/play/videos/cronicas/cronicas-huella-fuego-281116/3814720/)

- [Pausas, J., Vallejo, R. 2008. Bases ecológicas para convivir con los incendios forestales en la Región Mediterránea: decálogo. Ecosistemas, 17(2)](https://www.revistaecosistemas.net/index.php/ecosistemas/article/view/482)

- [Saeedreza M., Artemi C. 2024. The impacts of forest fires on watershed hydrological response. A review. Trees, Forests and People,  18, 100707](https://doi.org/10.1016/j.tfp.2024.100707)

- [Norlen, C.A. Hemes, K.S., Wang, J.A., Randerson, J.T., Battles, J.J., Tubbesing, C.L., Goulden, M.L. 2024 Recent fire history enhances semi-arid conifer forest drought resistance. Forest Ecology and Management, 573, 122331](https://doi.org/10.1016/j.foreco.2024.122331)

- [Lei, M. Cui, Y., Ni, J. et al. 2022. Temporal evolution of the hydromechanical properties of soil-root systems in a forest fire in China. Science of The Total Environment, 809, 151165](https://doi.org/10.1016/j.scitotenv.2021.151165)

- [Suárez-Muñoz, M., M. Mina, P. C. Salazar, R. M. Navarro-Cerrillo, J. L. Quero, and F. J. Bonet-García. 2021. A step-by-step guide to initialize and calibrate landscape models: A case study in the mediterranean mountains. Frontiers in Ecology and Evolution 9:209](https://doi.org/10.3389/fevo.2021.653393)

- [Flowchart - Wikipedia](https://en.wikipedia.org/wiki/Flowchart)
:::

# ¿Alguna duda?

- [bv2sumum@uco.es](mailto: bv2sumum@uco.es)

::: {.callout-tip}
# Si usas esta presentación puedes citarla como:
<small>**Suárez-Muñoz, M. **(2025). Introducción a la asignatura Ciclo de Gestión de los Datos. Máster Universitario en Conservación, Gestión y Restauración de la Biodiversidad. Universidad de Granada. [https://ecoinfugr.github.io/ecoinformatica/](https://ecoinfugr.github.io/ecoinformatica/) </small>
::: 


